Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,26 +30,43 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn clean verify -Dtestng.dtd.http=true
-    - name: Build and Run Tests
-      run: mvn test --batch-mode -Dmaven.test.failure.ignore=true
-    - name: Publish Test Report
-      uses: starburstdata/action-testng-report@v1
+    - name: Run tests
+      run: mvn test  # Adjust this command based on your Maven test process
+
+    - name: Generate TestNG report
+      run: mvn surefire-report:report-only  # Generate the XML reports
+
+    - name: Convert TestNG XML to HTML
+      run: java -cp target/dependency/*;target/test-classes;target/classes org.testng.TestNG target/surefire-reports/testng-results.xml
+
+    - name: Upload TestNG report
+      uses: actions/upload-artifact@v2
       with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+        name: testng-reports
+        path: target/surefire-reports/emailable-report.html  # Path to the HTML TestNG report
+  
+    
+    
+    #- name: Build and Run Tests
+     # run: mvn test --batch-mode -Dmaven.test.failure.ignore=true
+    #- name: Publish Test Report
+     # uses: starburstdata/action-testng-report@v1
+      #with:
+       #   github_token: ${{ secrets.GITHUB_TOKEN }}
           
-    - name: Archive Test Results 1
-      uses: actions/upload-artifact@v3
-      if: success() || failure()
-      with:
-        name: TestNG Emailable Report
-        path: test-output/emailable-report.html  
+   # - name: Archive Test Results 1
+    #  uses: actions/upload-artifact@v3
+     # if: success() || failure()
+     # with:
+      #  name: TestNG Emailable Report
+      #  path: test-output/emailable-report.html  
         
-    - name: Archive Test Results 2
-      uses: actions/upload-artifact@v3
-      if: success() || failure()
-      with:
-        name: TestNG Index Report
-        path: test-output/index.html
+    #- name: Archive Test Results 2
+     # uses: actions/upload-artifact@v3
+     # if: success() || failure()
+     # with:
+      #  name: TestNG Index Report
+       # path: test-output/index.html
           
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
